kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.48.1/deploy/static/provider/baremetal/deploy.yaml

--- watch ingress deployment ------
kubectl get pods -n ingress-nginx   -l app.kubernetes.io/name=ingress-nginx --watch
